namespace API.Dtos
{
    public class AdvToReturnDto
    {
        public int Id { get; set; }
        public string VnRetrofitType { get; set; }       

        public string NumParcAdv { get; set; }
        public string TypeBoitier { get; set; }
        public string Immatriculation { get; set; }
        public string Mec { get; set; }
        public string Statut { get; set; }
        public string CommentaireAdv { get; set; }
        public string Action { get; set; }
        public string OrderReceivedCompliant { get; set; }
        public string DateShipmentColumnAt { get; set; }
        public string Shipped { get; set; }
        public string Validated { get; set; }
        public string DateActivationAf3 { get; set; }
        public string InvoiceArtegy { get; set; }
        public string ClientOrderGiver { get; set; }
        public string EmailGenericPlatformAttachment { get; set; }
        public string NameCustomerDelivered { get; set; }
        public string OrderDate { get; set; }
        public string Vin { get; set; }
        public string Designation { get; set; }
        public string BrandModel { get; set; }
        public string StartDateVehicleAvailability { get; set; }
        public string EndDateVehicleAvailability { get; set; }
        public string Crc { get; set; }
        public string TypoKit { get; set; }
        public string Equipment1 { get; set; }
        public string Equipment2 { get; set; }
        public string Equipment3 { get; set; }
        public string Equipment4 { get; set; }
        public string Equipment5 { get; set; }
        public string AddressMountingNameComplement { get; set; }
        public string AddressMountingNumberOfTheStreet { get; set; }
        public string AddressMounting_Street { get; set; }
        public string AddressMountingPostalCode { get; set; }
        public string AddressMountingCity { get; set; }
        public string AddressMountingPhone { get; set; }
        public string ForecastDateOfBoxAssembly { get; set; }
        public string TachographMounted { get; set; }
        public string DigitallyEnabledCommunicatingTachograph { get; set; }
        public string NameOfManager { get; set; }
        public string NameOfTechnicianAdv { get; set; }
        public string AccessEcoDriving { get; set; }
        public string Access_telematic { get; set; }
        public string OptionGeolocation { get; set; }
        public string OptionSocialData1 { get; set; }
        public string OptionSocialData2 { get; set; }
        public string OptionSpecific1 { get; set; }
        public string SoftwareVersion { get; set; }
        public string BoxConfiguration { get; set; }
        public string ArticleTelematic1 { get; set; }
        public string CodeArticle1 { get; set; }
        public string PriceArticle1 { get; set; }
        public string ArticleTelematic2 { get; set; }
        public string CodeArticle2 { get; set; }
        public string PriceArticle2 { get; set; }
        public string ArticleTelematic3 { get; set; }
        public string CodeArticle3 { get; set; }
        public string PriceArticle3 { get; set; }
        public string ArticleTelematic4 { get; set; }
        public string CodeArticle4 { get; set; }
        public string PriceArticle4 { get; set; }
        public string ArticleTelematic5 { get; set; }
        public string ArticleTelematic6 { get; set; }
        public string ArticleTelematic7 { get; set; }
        public string ArticleTelematic8 { get; set; }
        public string ArticleTelematic9 { get; set; }
        public string ArticleTelematic10 { get; set; }
        public string ForRent { get; set; }
        public string InstallMonth { get; set; }
        public string BoxPosed { get; set; }
        public string DeviceId { get; set; }
        public string Sn { get; set; }
        public string NumSim { get; set; }
        public string Msisdn { get; set; }
        public string Observation { get; set; }
        public string AddressMountingName { get; set; }
        public string ChassisAddressName { get; set; }
        public string ChassisAddressNumberOfTheStreet { get; set; }
        public string ChassisAddressStreet { get; set; }
        public string ChassisAddressPostalCode { get; set; }
        public string ChassisAddressCity { get; set; }
        public string ChassisAddressPhone { get; set; }
    }
}